# Generated by Django 4.2.30 on 2026-06-06 05:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apibackendapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('ProjectID', models.AutoField(primary_key=True, serialize=False)),
                ('ProjectName', models.CharField(max_length=150)),
                ('Description', models.TextField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('Budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('IsActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='dept_code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dept_name',
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='department_code',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='department_name',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Designation', models.CharField(max_length=100)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DateOfJoining', models.DateField()),
                ('Contact', models.CharField(max_length=15)),
                ('IsActive', models.BooleanField(default=True)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='apibackendapp.department')),
                ('Projects', models.ManyToManyField(related_name='employees', to='apibackendapp.project')),
            ],
        ),
    ]
